apiVersion: v1
kind: Template
metadata:
  name: pv-template
  annotations:
    description: "Description"
    iconClass: "icon-minio"
    tags: "database,nosql"
objects:
- apiVersion: "v1"
  kind: PersistentVolumeClaim
  metadata:
    name: "claim1"
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "pv0001"
